apiVersion: v1
kind: ConfigMap
metadata:
  name: wezvabackendapp
  namespace: wezvatech
data:
   application.properties: |

        logging.level.org.springframework=INFO
        logging.level.com.mkyong=INFO
        logging.level.com.zaxxer=ERROR
        logging.level.root=ERROR

        # Enable the Spring Boot Actuator endpoint over HTTP & Prometheus
        management.endpoints.web.exposure.include=*
        management.endpoints.web.exposure.exclude=

        # Enable healthcheck probes for kubernetes
        management.endpoint.health.probes.enabled=true

        spring.datasource.hikari.connectionTimeout=20000
        spring.datasource.hikari.maximumPoolSize=5

        # logging.pattern.console=%-5level %logger{36} - %msg%n

        ## MySQL
        #spring.datasource.url=jdbc:mysql://localhost:3306/mywezvadb
        spring.datasource.url=jdbc:mysql://mysql-svc/mywezvadb
        spring.datasource.username=${MYSQL_USER}
        spring.datasource.password=${MYSQL_PASSWORD}

        # hibernate_sequence' doesn't exist
        # spring.jpa.hibernate.use-new-id-generator-mappings=false

        # drop n create table again, good for testing, comment this in production
        spring.jpa.hibernate.ddl-auto=create-drop

