kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: mysql
  name: mysql
  namespace: wezvatech
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - image: mysql:8.1
          name: mysql
          ports:
          - containerPort: 3306
          readinessProbe:
           tcpSocket:
              port: 3306
           initialDelaySeconds: 30
           timeoutSeconds:  5
           periodSeconds: 5
          env:
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-creds
                  key: username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-creds
                  key: password
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-creds
                  key: rootpassword
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mysql-creds
                  key: database
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-creds
  namespace: wezvatech
type: Opaque
stringData:
  password: password
  username: wezvatech
  rootpassword: password
  database: mywezvadb
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql
  name: mysql-svc
  namespace: wezvatech
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: mysql
  type: NodePort

